--- #YAML:1.0
name: Module-Build
version: 0.18_01
license: perl
distribution_type: module
requires:
  Config: 0
  Cwd: 0
  Data::Dumper: 0
  ExtUtils::Install: 0
  File::Basename: 0
  File::Compare: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  IO::File: 0
  perl: 5.005_03
recommends:
  Archive::Tar: 0.23
  ExtUtils::Install: 0.3
  ExtUtils::ParseXS: 2.02
  Module::Info: 0
  YAML: 0.35
build_requires:
  Test: 0
conflicts: {}
provides:
  Module::Build:
    file: lib/Module/Build.pm
    version: 0.18_01
  Module::Build::Base:
    file: lib/Module/Build/Base.pm
    version: ~
  Module::Build::Compat:
    file: lib/Module/Build/Compat.pm
    version: 0.02
  Module::Build::PPMMaker:
    file: lib/Module/Build/PPMMaker.pm
    version: ~
  Module::Build::Platform::Amiga:
    file: lib/Module/Build/Platform/Amiga.pm
    version: ~
  Module::Build::Platform::Default:
    file: lib/Module/Build/Platform/Default.pm
    version: ~
  Module::Build::Platform::EBCDIC:
    file: lib/Module/Build/Platform/EBCDIC.pm
    version: ~
  Module::Build::Platform::MPEiX:
    file: lib/Module/Build/Platform/MPEiX.pm
    version: ~
  Module::Build::Platform::MacOS:
    file: lib/Module/Build/Platform/MacOS.pm
    version: ~
  Module::Build::Platform::RiscOS:
    file: lib/Module/Build/Platform/RiscOS.pm
    version: ~
  Module::Build::Platform::Unix:
    file: lib/Module/Build/Platform/Unix.pm
    version: ~
  Module::Build::Platform::VMS:
    file: lib/Module/Build/Platform/VMS.pm
    version: ~
  Module::Build::Platform::VOS:
    file: lib/Module/Build/Platform/VOS.pm
    version: ~
  Module::Build::Platform::Windows:
    file: lib/Module/Build/Platform/Windows.pm
    version: ~
  Module::Build::Platform::Windows::BCC:
    file: lib/Module/Build/Platform/Windows.pm
    version: ~
  Module::Build::Platform::Windows::GCC:
    file: lib/Module/Build/Platform/Windows.pm
    version: ~
  Module::Build::Platform::Windows::MSVC:
    file: lib/Module/Build/Platform/Windows.pm
    version: ~
  Module::Build::Platform::darwin:
    file: lib/Module/Build/Platform/darwin.pm
    version: ~
generated_by: Module::Build version 0.18_01
