--- #YAML:1.0
name: Module-Build
version: 0.14
license: perl
distribution_type: module
requires:
  Config: 0
  Cwd: 0
  Data::Dumper: 0
  ExtUtils::Install: 0
  File::Basename: 0
  File::Compare: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  File::Spec: 0
  perl: 5.6.0
recommends:
  Archive::Tar: 0.22
  ExtUtils::Install: 0.3
  ExtUtils::ParseXS: 0
  YAML: 0.35
build_requires:
  Test: 0
conflicts: {}
generated_by: Module::Build version 0.14
