--- #YAML:1.0
name: Sample
version: 0.01
author:
  - Sample Man <sample@example.com>
abstract: Foo foo sample foo
license: perl
requires:
  File::Spec: 0
provides:
  Sample:
    file: lib/Sample.pm
    version: 0.01
  Sample::NoPod:
    file: lib/Sample/NoPod.pm
generated_by: Module::Build version 0.25_03
