--- #YAML:1.0
build_requires: {}
conflicts: {}
distribution_type: module
dynamic_config: 0
generated_by: Module::Build version 0.13
license: unknown
name: Sample
recommends: {}
requires: {}
version: 0.01
